# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc

# Build the HTML docs with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Install Python dependencies for building the docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
